sudo: required
service:
    - docker

before_install:
    - docker build -t salperes/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true salperes/docker-react npm run test -- --coverage
#    - docker run -e CI=true -v /app/node_modules -v $(pwd):/app 6d99620449dd npm run test -- --coverage

 
#    - docker run -e CI=true salperes/docker-react npm run test
#language: generic 

deploy:
    provider: elasticbeanstalk

    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-943065502433"
    bucket_path: "docker-react"

    on:
        branch: main


    access_key_id: $aws_access_key
    secret_access_key: $aws_secret_key
    